# PlantUML Editor

1. select template
2. write uml diagram

@startuml Bókhald
left to right direction

class Vinnuferð {
  Flugferð út
  Flugferð inn
  áfangastaður
  dags og tími brottfarar frá Íslandi
  dags og tíma brottfarar til Íslands
  updateVoyage()
  checkPilotsAndAtten()
  staffVoyage()
}

object Flugferð {
  upphafsstaður
  upphafstími
  áfangastaður
  komutími
}


class Starfsmenn {
  listOfEmployees
  addEmployee(info)
  listSpecificEmployee(kennitala)
  changeEmployeeInfo(kennitala,changeInfo)
  listAllEmployees()
  listAllPilots()
  listAllAttend()
}

object Starfsmaður {
  nafn
  kennitala
  heimilisfang
  heimasími
  gsmsími
  netfang
}


object Áfangastaður {
  land
  flugvöllur
  flugtími
  fjarlægð
  tengiliður
  neyðarsímanúmer
}


class Bókhald {
  vinnuferðir
  schedule
  starfsmenn
  addVoyage()
  recurringVoyage()
  listAllEmployeeNotworkDay()
  listAllEmployeeSpecificDay()
  ListAllVoyagesOfEmployeeSpecificWeek()
}

object Flugmaður {
  flugmaður
  isCaptain
}

object Flugþjónn {
  flugþjónn
  isManager
}

Vinnuferð -|| "1" Áfangastaður
Vinnuferð "1" --{ "2" Flugferð
Bókhald o-- Vinnuferð
Starfsmaður --|> Flugmaður
Starfsmaður --|> Flugþjónn
Flugmaður --* Starfsmenn
Flugþjónn --* Starfsmenn
Vinnuferð --{ "2. Flugmenn" Starfsmenn
Vinnuferð -|| "1. Flugþjón" Starfsmenn
@enduml