@startuml 
  
state get_shifts {
  state get_shifts as "Ná í vinnuyfirlit"
    get_shifts : do/ skilar lista með listum (dagar > vinnuferðir > starfsfólk)
  
  state input_date as "innslá dags."
  state how_many_days as "spyrja: hversu margir dagar? 1-7"
    how_many_days : hversu margir dagar frá tilteknum degi á að birta

  state get_voyages {
    state get_voyages as "ná í vinnuferðir"
      get_voyages : do/ forLoop, skilar lista af vinnuferðum fyrir x marga daga
      get_voyages : entry/ 'X', skilar X mörgum dögum
    state fetch_voyages as "finna vinnuferðir dagsins"
    state make_days_list as "bæta á lista af dögum"
      make_days_list : do/ return list of voyages per day

    [*] --> fetch_voyages
    fetch_voyages --> make_days_list
    make_days_list --> fetch_voyages : loop X times
    make_days_list --> [*] : skilar X mörgum dögum
  }

  [*] --> input_date
  input_date --> input_date : incorrect input/ \nekki rétt format á dags.
  input_date --> how_many_days
  how_many_days --> get_voyages
    how_many_days --> how_many_days : not within range/ \n not a integer
  get_voyages --> [*] : skilar lista með x mögum dögum
}

state display_shifts {
  state display_shifts as "birta vinnuyfirlit"
    display_shifts : do/ spyrja hvort eigi að birta "á vakt" eða "ekki á vakt"

  state get_on_shift as "á vakt"
    get_on_shift : do/ forLoop, birtir hverjir voru á vakt hvern dag
  state get_off_shift as "ekki á vakt"
    get_off_shift : do/ forLoop, athugar hverjir voru ekki á vakt hvern dag
  state print_shifts as "prenta vaktirnar"
    print_shifts : do/ prentar út hverjir eru á vakt (eða ekki) á hverjum degi fyrir sig

  [*] --> get_on_shift
  [*] --> get_off_shift
  get_on_shift --> print_shifts
  get_off_shift --> print_shifts

}
get_shifts --> display_shifts
@enduml