@startuml 

state create_voyage {
  state create_voyage as "skrá nýja vinnuferð"
    create_voyage : do/ byðja um upplýsingar frá input
    create_voyage : exit/ ef notandi hættir við skráningu /staðfestir ekki gögnin

  state input_destination {
    state input_destination as "áfangastaður"
      input_destination : leita að áfangastað af lista eða slá inn nafn áfangastaðar
    state destination_search as "leita að áfangastað"
      destination_search : fall sem birtir áfangastaði til að velja
    state destination_direct as "slá inn áfangastað"
    [*] --> destination_direct
    [*] --> destination_search
    destination_direct --> destination_direct : áfangastaður ekki til/ \n"incorrect input"
    destination_search --> [*]
    destination_direct --> [*] : áfangastaður fannst
  }
  state input_date_out as "dagur/tími brottfarar (út)"
  state input_date_in as "dagur/tími brottfarar (heim)"
  state input_plane {
    state input_plane as "velja flugvél"
    state plane_search as "leita að flugvél" 
      plane_search : fall sem birtir lausar flugvélar til að velja
    state plane_direct as "slá inn nafn flugvélar"

    [*] --> plane_search
    [*] --> plane_direct
    plane_direct --> plane_direct : engin flugvél laus fyrir þessa ferð/ \n"incorrect input"
    plane_direct --> [*]
    plane_search --> [*]
  }
  state voyage_confirm as "staðfesta upplýsingar / vista"
    voyage_confirm : do/ prenta innslegnar upplýsingar
    voyage_confirm : do/ spyrja notanda hvort upplýsingar séu réttar "já/nei"
    voyage_confirm : exit/ "já" : gögnin vistuð í kerfið
    voyage_confirm : exit/ "nei" : gögn ekki vistuð,  fer til baka í "skrá ný gögn"

  state repeat_voyage {
    state repeat_voyage as "endurtaka vinnuferð"
    state repeat_pattern as "endurtaka mynstur"
      repeat_pattern : x margir dagar milli endurtakninga
    state repeat_dates {
      state repeat_dates as "endurtaka á tilteknum dagsetn."
        repeat_dates : do/ while loop, biður um dagsetningar
      ' state repeat_date_input as "slá inn dags."
      '   repeat_date_input : entry/ 'true', tókst að bæta dags. á listann
      '   repeat_date_input : entry/ 'false',  
      ' state repeat_date_check as "athuga dags."
      '   repeat_date_check : do/ athuga hvort flugvöllur og flugvél sé laus
      '   repeat_date_check : exit/ tími hentar hentar fyrir vinnuferð, bæta dags á lista.
      '   repeat_date_check : exit/ engin flugvél laus, gefur error skilaboð
      ' state repeat_date_end as "birta lista af innslegnum dags."

      ' [*] --> repeat_date_input 
      ' repeat_date_input --> repeat_date_input : 'invalid input'
      ' repeat_date_input --> repeat_date_check : valid date
      ' repeat_date_check --> repeat_date_input : 'return false'
      ' repeat_date_check --> repeat_date_input : 'return true'
    }
    state repeat_confirm as "staðfesta endurtekningar"
      repeat_confirm : do/ prenta lista af endurteknum vinnuferðum
      repeat_confirm : exit/ 'já', vistar nýju vinnuferðirnar í kerfið
      repeat_confirm : exit/ 'nei', fær kost á að breyta tilfelfellum
      repeat_confirm : exit/ 'hætta við', fer aftur á 'skrá ný gögn' án þess að vista 
    state edit_repeats as "breyta endurtekningum"
    [*] --> repeat_pattern
    [*] --> repeat_dates
    repeat_pattern --> repeat_confirm
    repeat_dates --> repeat_confirm
    repeat_confirm --> [*] : 'já'
    repeat_confirm --> edit_repeats : 'nei'
    repeat_confirm --> [*] : 'hætta við'
    edit_repeats --> repeat_confirm
    
    
  }

  [*] -right-> input_destination
  input_destination --> input_date_out : áfangastaður fannst
  input_date_out --> input_date_in : flugvöllur laus á þessum tíma
    input_date_out --> input_date_out : flugvöllur upptekinn á þessum tíma/ \n"incorrect input"
  input_date_in --> input_plane : tími/dags frá brottför út er ekki \nstyttri en flugtími til áfangastaðar
    input_date_in --> input_date_in : flugvel væri ekki búin að lenda úti/ \n"incorrect input"
  input_plane --> voyage_confirm : laus flugvél fannst fyrir ferðina
  voyage_confirm -right-> [*] : 'nei', hættir við skráningu
  voyage_confirm -right-> repeat_voyage : 'já'
  repeat_voyage --> [*] : lýkur við ferlið
  
}



[*] --> create_voyage : velur að skrá nýja vinnuferð
create_voyage --> [*] : fer aftur á "skrá ný gögn"


@enduml