# PlantUML Editor

@startuml Klasarit
object UI {
    Navigator() //works as main, calls Menu to navigate
}

class Menu {
    //takes care of menus and knows when
    //to contact lower level with input
    ScreenPrinter()
    input()
}

object Vinnslulag {
    UISupplier() //works as main, returns printable string to UI
    dataPipe() //params control fetching or returning file package
}

class Writer {
    //creating a voyage has 
    //special rules, Voyager
    // takes care of them
    NewEmployee()
    NewPilot()
    NewAttendant()
    NewDestination()
    NewVoyage()
    NewPlane()
}

class Voyager {
    //makes sure staff is only on this one voyage
    //makes sure staff includes two pilots and an Attendant

    CheckStaff() //gate for valid employees
    UpdateVoyage() //if everything checks out
}

class Finder {
    //simplest class, gets all his data from getDate in UISupplier
    //and simply sorts through the data to return
    //relevant info as a printable string
    AllPilots()
    AllAttend()
    AllEmployees()
    AllDestintions()
    SpecificEmployee()
    ListVoyages()
    ListAllEmployeeNotWorkingSpecificDay()
    ListAllEmployeeAreWorkingSpecificDayAndDestinations()
    AllVoyagesOfEmployeeSpecificWeek()
}

class Updater {
    //finds data to update and overwrites
    ifExists()
    OverwriteEmployee()
    updateVoyage()
}

object Gagnalag {
    //either sends file package to OverWriter or returns a file package from Opener
    DataLayer() //main, params control fetch or replace
}

class Overwriter {
    //takes file package and writes over all files with updated data
    WriteToFile(fileinfo) //both for updates and appends, overwrites file
}

class Opener {
    //fetches all data and bundles it into a dictionary with lists of lines
    OpenFile(filename, readOrWrite) //main, opens filestream of relevant file
    Lister(filestream) //reads file, makes a list of lines
    DictionMaker(fileinfo) //creates dictionary of list of lines
}

object DataPipe {
    
}
UI --- Vinnslulag
UI --- Menu
Vinnslulag --- Finder
Vinnslulag --- Gagnalag
Vinnslulag --- Writer
Vinnslulag --- Updater
Updater --- Voyager
Writer  --- Voyager
Gagnalag --- Opener
Gagnalag --- Overwriter
@enduml